name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker container
      run: |
        docker build . -t stockfx
    - uses: actions/upload-artifact@v1 
      with:
       name: Images
       path: Images/stockfx
